"""Instagram AI Manager Integration (module brief, section 17):
"After creating a Reel provide: [Open Instagram Manager]. Pass: video
project, Reel title, hook, caption, CTA, hashtags, suggested posting
time, cover. The Instagram Manager should be able to use the generated
content."

This module is the hand-off itself - it generates hooks/caption/CTA/
hashtags GROUNDED IN THE ACTUAL VIDEO (via a content_description built
from the video's own transcript and reel plan, never a generic topic
guess) by calling jarvis.instagram_ai_manager.ai_services' ALREADY
EXISTING, already-tested generate_hooks()/generate_caption()/
generate_cta()/generate_hashtags() functions directly - per this
project's "Do not duplicate existing AI infrastructure" rule, this
module adds NO new LLM-calling code of its own for that content; it
only builds the input text those functions need and saves their output
through jarvis.instagram_ai_manager.db's own save_hook_set()/
save_caption()/save_cta_set()/save_hashtag_set(), so the result appears
directly in the existing Instagram AI Manager UI (Content Studio tab)
exactly like anything generated there natively - no separate "video
studio content" concept for Instagram AI Manager to know about.

Suggested posting time and the cover image are NOT generated by
jarvis.instagram_ai_manager.ai_services (it has no such generator) -
suggested posting time instead reuses jarvis.instagram_ai_manager
.analytics_services.analyze_posting_times() (real Instagram data, if
connected) when available, and the cover is simply the already-
rendered jarvis.video_studio.cover output file's path, both passed
through untouched (see HandoffResult below) rather than invented here.
"""

from __future__ import annotations

from dataclasses import dataclass

from jarvis.core.llm import LLMClient
from jarvis.instagram_ai_manager import ai_services, db as ig_db
from jarvis.video_studio.reel import ReelEditPlan


def _build_content_description(transcript_text: str, plan: ReelEditPlan | None) -> str:
    """Builds the "topic"/"content_description" text
    jarvis.instagram_ai_manager.ai_services' generators need, grounded
    in what this specific video actually contains - never a generic
    placeholder. Prefers the reel plan's clip captions (already a
    distilled, curated summary of the video's key moments) when a plan
    exists, falling back to a truncated transcript otherwise."""
    if plan is not None and plan.clips:
        captions = " / ".join(c.caption_text for c in plan.clips)
        return f"{captions}. {transcript_text.strip()[:400]}".strip()
    return transcript_text.strip()[:500]


@dataclass(frozen=True)
class HandoffResult:
    hook_set_id: int | None
    caption_id: int | None
    cta_set_id: int | None
    hashtag_set_id: int | None
    cover_path: str | None
    suggested_posting_time: str | None
    insufficient_data: bool
    message: str | None
    """Set (True/non-None) only if EVERY generator failed - a partial
    result (e.g. hooks generated but caption generation failed) is
    still reported as insufficient_data=False, since some content did
    reach Instagram AI Manager; the caller inspects which *_id fields
    are None to know what specifically didn't make it, same "partial
    success is still useful" reasoning
    jarvis.instagram_ai_manager.ai_services.generate_hooks() itself
    already applies to its own per-category results."""


def send_to_instagram_manager(
    llm: LLMClient, *, transcript_text: str, plan: ReelEditPlan | None,
    cover_path: str | None, tone: str = "friendly",
) -> HandoffResult:
    """The module's main entry point - generates hook/caption/CTA/
    hashtag content grounded in this video (via
    jarvis.instagram_ai_manager.ai_services, never duplicated logic -
    see this module's own docstring) and saves each into
    jarvis.instagram_ai_manager.db, so it appears in the existing
    Instagram AI Manager Content Studio UI. Never raises - a
    generator's own None-on-failure result is simply skipped (that
    piece of content isn't saved, its *_id stays None), matching
    ai_services' own "never raise, return None on failure" contract."""
    content_description = _build_content_description(transcript_text, plan)
    if not content_description.strip():
        return HandoffResult(
            hook_set_id=None, caption_id=None, cta_set_id=None, hashtag_set_id=None,
            cover_path=cover_path, suggested_posting_time=None, insufficient_data=True,
            message="No transcript or Reel plan is available yet - transcribe the video and create a Reel first.",
        )

    hook_set_id: int | None = None
    hooks = ai_services.generate_hooks(llm, content_description)
    chosen_hook: str | None = None
    if hooks:
        hook_set_id = ig_db.save_hook_set(content_description, hooks)
        chosen_hook = plan.hook if plan is not None else next(iter(next(iter(hooks.values()), [])), None)

    caption_id: int | None = None
    caption = ai_services.generate_caption(
        llm, topic=content_description, content_description=content_description,
        hook=chosen_hook, tone=tone, target_audience=None,
        cta=plan.cta if plan is not None else None,
    )
    if caption:
        caption_id = ig_db.save_caption(content_description, tone, caption)

    cta_set_id: int | None = None
    ctas = ai_services.generate_cta(llm, content_description)
    if ctas:
        cta_set_id = ig_db.save_cta_set(content_description, ctas)

    hashtag_set_id: int | None = None
    hashtags = ai_services.generate_hashtags(llm, content_description)
    if hashtags:
        hashtag_set_id = ig_db.save_hashtag_set(content_description, hashtags)

    suggested_posting_time = _suggested_posting_time()

    if hook_set_id is None and caption_id is None and cta_set_id is None and hashtag_set_id is None:
        return HandoffResult(
            hook_set_id=None, caption_id=None, cta_set_id=None, hashtag_set_id=None,
            cover_path=cover_path, suggested_posting_time=suggested_posting_time,
            insufficient_data=True, message="AI generation failed for every content type - try again.",
        )

    return HandoffResult(
        hook_set_id=hook_set_id, caption_id=caption_id, cta_set_id=cta_set_id,
        hashtag_set_id=hashtag_set_id, cover_path=cover_path,
        suggested_posting_time=suggested_posting_time, insufficient_data=False, message=None,
    )


def _suggested_posting_time() -> str | None:
    """Reuses jarvis.instagram_ai_manager.analytics_services
    .analyze_posting_times() (real Instagram data via the existing,
    already-connected InstagramConnector) rather than inventing a
    posting-time heuristic here - returns None (not a guess) if
    Instagram isn't connected or there isn't enough data, per that
    function's own insufficient_data/data_confidence guarantees (see
    its docstring: "NEVER claims a universally 'best' time")."""
    try:
        from jarvis.instagram_ai_manager import analytics_services
        from jarvis.integrations.connectors.instagram import InstagramConnector

        connector = InstagramConnector()
        if not connector.is_configured():
            return None
        analysis = analytics_services.analyze_posting_times(connector)
    except Exception:
        return None

    if analysis.insufficient_data or not analysis.best_days or not analysis.best_hours:
        return None
    return f"{analysis.best_days[0]} around {analysis.best_hours[0]} ({analysis.data_confidence} confidence)"
