"""Instagram AI Manager Integration (module brief, section 16): "Send
the generated Reel package to the existing Instagram AI Manager. The
Instagram Manager should receive: video, cover, caption, CTA,
hashtags, topic, suggested posting time. Do NOT automatically publish.
Require user approval before publishing."

Copies jarvis.video_studio.instagram_handoff's exact mechanism (see
that module's own docstring for the full rationale) - a direct Python
function call into jarvis.instagram_ai_manager.ai_services/.db, no new
LLM-calling logic of its own for hook/caption/CTA/hashtag text. For a
Mode B (from-idea) Reel, the caption/hashtags this module sends were
already generated by jarvis.reel_generator.caption
.generate_reel_caption_package() during Stage 2 and are simply
forwarded here (never re-generated) - only hooks are generated fresh
here, since Stage 2 has no hook-generation step of its own. For a Mode
A (from-footage) Reel, this module calls
jarvis.instagram_ai_manager.ai_services directly (same as
jarvis.video_studio.instagram_handoff already does for a Video-Studio-
native Reel), grounded in the plan's own hook/CTA/clip captions.

Never publishes anything - this module's only job is making the
content available in Instagram AI Manager's own Content Studio UI
(exactly as if generated there natively), where a person can review and
publish it themselves through that module's own existing, separate
publish flow (outside this module's scope entirely)."""

from __future__ import annotations

from dataclasses import dataclass

from jarvis.core.llm import LLMClient
from jarvis.instagram_ai_manager import ai_services
from jarvis.instagram_ai_manager import db as ig_db
from jarvis.reel_generator.brief import ReelBrief
from jarvis.reel_generator.caption import ReelCaptionPackage
from jarvis.reel_generator.script import ReelScript
from jarvis.video_studio.reel import ReelEditPlan


@dataclass(frozen=True)
class HandoffResult:
    hook_set_id: int | None
    caption_id: int | None
    cta_set_id: int | None
    hashtag_set_id: int | None
    cover_path: str | None
    video_path: str | None
    suggested_posting_time: str | None
    insufficient_data: bool
    message: str | None
    """Set (True/non-None) only if EVERY piece of content failed to
    reach Instagram AI Manager - a partial result (e.g. hooks sent but
    caption failed) is still reported as insufficient_data=False, same
    "partial success is still useful" convention as
    jarvis.video_studio.instagram_handoff.HandoffResult."""


def _suggested_posting_time() -> str | None:
    """Identical to jarvis.video_studio.instagram_handoff's own private
    helper of the same purpose - reuses jarvis.instagram_ai_manager
    .analytics_services.analyze_posting_times() (real Instagram data,
    if connected) rather than inventing a heuristic. Returns None (not
    a guess) if Instagram isn't connected or there isn't enough data."""
    try:
        from jarvis.instagram_ai_manager import analytics_services
        from jarvis.integrations.connectors.instagram import InstagramConnector

        connector = InstagramConnector()
        if not connector.is_configured():
            return None
        analysis = analytics_services.analyze_posting_times(connector)
    except Exception:
        return None

    if analysis.insufficient_data or not analysis.best_days or not analysis.best_hours:
        return None
    return f"{analysis.best_days[0]} around {analysis.best_hours[0]} ({analysis.data_confidence} confidence)"


def send_idea_reel_to_instagram_manager(
    llm: LLMClient, *, brief: ReelBrief, script: ReelScript, caption_package: ReelCaptionPackage,
    cover_path: str | None, export_path: str | None, tone: str = "friendly",
) -> HandoffResult:
    """Hand-off for a Mode B (from-idea) Reel. The caption/hashtags
    were already generated in Stage 2 (jarvis.reel_generator.caption) -
    forwarded here as-is, never re-generated, so what a person already
    reviewed in AI Reel Generator is exactly what lands in Instagram AI
    Manager. Only hooks are generated fresh (Stage 2 has no hook step
    of its own) via jarvis.instagram_ai_manager.ai_services
    .generate_hooks(), grounded in the approved script's own text.
    Never raises."""
    content_description = script.full_text
    if not content_description.strip():
        return HandoffResult(
            hook_set_id=None, caption_id=None, cta_set_id=None, hashtag_set_id=None,
            cover_path=cover_path, video_path=export_path, suggested_posting_time=None,
            insufficient_data=True, message="This Reel has no script text yet - approve a script first.",
        )

    hook_set_id: int | None = None
    hooks = ai_services.generate_hooks(llm, content_description)
    if hooks:
        hook_set_id = ig_db.save_hook_set(content_description, hooks)

    caption_id: int | None = None
    if caption_package.caption:
        caption_id = ig_db.save_caption(brief.topic, tone, caption_package.caption)

    hashtag_set_id: int | None = None
    if caption_package.hashtags:
        hashtag_set_id = ig_db.save_hashtag_set(brief.topic, caption_package.hashtags)

    cta_set_id: int | None = None
    ctas = ai_services.generate_cta(llm, brief.topic)
    if ctas:
        cta_set_id = ig_db.save_cta_set(brief.topic, ctas)

    suggested_posting_time = _suggested_posting_time()

    if hook_set_id is None and caption_id is None and cta_set_id is None and hashtag_set_id is None:
        return HandoffResult(
            hook_set_id=None, caption_id=None, cta_set_id=None, hashtag_set_id=None,
            cover_path=cover_path, video_path=export_path, suggested_posting_time=suggested_posting_time,
            insufficient_data=True, message="AI generation failed for every content type - try again.",
        )

    return HandoffResult(
        hook_set_id=hook_set_id, caption_id=caption_id, cta_set_id=cta_set_id, hashtag_set_id=hashtag_set_id,
        cover_path=cover_path, video_path=export_path, suggested_posting_time=suggested_posting_time,
        insufficient_data=False, message=None,
    )


def _build_footage_content_description(plan: ReelEditPlan) -> str:
    """Same shape as jarvis.video_studio.instagram_handoff
    ._build_content_description() - grounds the description in the
    plan's own hook + per-clip captions, never a generic placeholder."""
    captions = " / ".join(c.caption_text for c in plan.clips)
    return f"{plan.hook}. {captions}. {plan.cta}".strip()


def send_footage_reel_to_instagram_manager(
    llm: LLMClient, *, plan: ReelEditPlan, export_path: str | None, tone: str = "friendly",
) -> HandoffResult:
    """Hand-off for a Mode A (from-footage) Reel - identical mechanism
    to jarvis.video_studio.instagram_handoff.send_to_instagram_manager()
    (this Reel's own plan already came from that same video_studio
    pipeline - see jarvis.reel_generator.footage's own docstring), just
    grounded in the plan directly rather than a raw transcript, and
    returning this module's own HandoffResult shape (which additionally
    carries video_path, since a Reel - unlike a bare video_studio
    project - is the primary artifact this module hands off). Never
    raises."""
    if plan.insufficient_data or not plan.clips:
        return HandoffResult(
            hook_set_id=None, caption_id=None, cta_set_id=None, hashtag_set_id=None,
            cover_path=None, video_path=export_path, suggested_posting_time=None,
            insufficient_data=True, message="This Reel has no usable edit plan yet.",
        )

    content_description = _build_footage_content_description(plan)

    hook_set_id: int | None = None
    hooks = ai_services.generate_hooks(llm, content_description)
    chosen_hook = plan.hook
    if hooks:
        hook_set_id = ig_db.save_hook_set(content_description, hooks)

    caption_id: int | None = None
    caption = ai_services.generate_caption(
        llm, topic=content_description, content_description=content_description,
        hook=chosen_hook, tone=tone, target_audience=None, cta=plan.cta,
    )
    if caption:
        caption_id = ig_db.save_caption(content_description, tone, caption)

    cta_set_id: int | None = None
    ctas = ai_services.generate_cta(llm, content_description)
    if ctas:
        cta_set_id = ig_db.save_cta_set(content_description, ctas)

    hashtag_set_id: int | None = None
    hashtags = ai_services.generate_hashtags(llm, content_description)
    if hashtags:
        hashtag_set_id = ig_db.save_hashtag_set(content_description, hashtags)

    suggested_posting_time = _suggested_posting_time()

    if hook_set_id is None and caption_id is None and cta_set_id is None and hashtag_set_id is None:
        return HandoffResult(
            hook_set_id=None, caption_id=None, cta_set_id=None, hashtag_set_id=None,
            cover_path=None, video_path=export_path, suggested_posting_time=suggested_posting_time,
            insufficient_data=True, message="AI generation failed for every content type - try again.",
        )

    return HandoffResult(
        hook_set_id=hook_set_id, caption_id=caption_id, cta_set_id=cta_set_id, hashtag_set_id=hashtag_set_id,
        cover_path=None, video_path=export_path, suggested_posting_time=suggested_posting_time,
        insufficient_data=False, message=None,
    )
