"""Per-scene visual plan - shared by AI Reel Generator (this feature's
own "Smart Visual Director" brief) and jarvis.story_generator (that
feature's own earlier visual-richness brief, requirements 1-7): the
structured description of HOW a scene should actually look and move,
beyond its plain on_screen_text/visual_description
(jarvis.reel_generator.storyboard.Scene's own fields, unchanged) -
visual type/source, supporting visual elements, on-screen text cue
timing/position/animation, an optional sticker/emoji, motion, and
emotional direction (pacing/lighting).

Originally written for jarvis.story_generator (see that package's own
history), PROMOTED here once AI Reel Generator's own Smart Visual
Director brief needed the exact same shape - rather than duplicate
ScenePlan/TextCue/VisualPlan and their Pillow-compositing rendering
code a second time, both features import this one shared module and
each writes its own LLM prompt against it (jarvis.reel_generator
.storyboard's own scene generation, jarvis.story_generator.story_scenes'
own). jarvis.story_generator now imports ScenePlan/TextCue/VisualPlan
FROM here rather than defining its own copy - see that package's own
modules for the re-export.

Generated by the SAME LLM call that produces each feature's own Scene
list (no second round-trip), one ScenePlan per Scene, matched by scene
number. Stored as its own JSON blob, separate from a project's
storyboard data, so a project saved before this plan existed (or one
whose plan failed to parse) degrades gracefully to a plain scene render
- jarvis.reel_generator.scenes.render_all_scenes() and
jarvis.reel_generator.scene_render.render_all_story_scenes() both
already work from Scene alone; a ScenePlan only ever ADDS detail on top
of what a Scene already provides, never replaces it.

Rendering (turning a ScenePlan into actual pixels/motion in the
exported video) is a SEPARATE stage - jarvis.reel_generator.scene_render
(main visual/supporting visuals/text cues/stickers all composited via
Pillow) and an optional motion_by_scene passed to
jarvis.reel_generator.export.export_reel_video() (Ken Burns pan/zoom via
ffmpeg's zoompan filter) - this module only defines and validates the
PLAN's shape; see either of those modules' own docstrings for why they
are kept separate from planning."""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass

# Requirement 1 (AI Reel Generator's own Smart Visual Director brief):
# "Choose between: AI-generated image / uploaded user photo / product
# photo / stock-style/B-roll visual / video clip / animated background /
# typography-focused scene." No AI image/video generation exists in
# this codebase (confirmed repeatedly across this whole project's
# history) - so "ai_generated"/"b_roll"/"animated_background" all map
# to a distinct Pillow rendering TREATMENT (background style/
# composition), never an actual generated photo/video source.
# "uploaded_photo"/"video_clip" are the two sources that ARE genuinely
# real when the person actually supplies their own file (see
# jarvis.reel_generator.scenes' own uploaded_image_path handling and
# jarvis.reel_generator.scene_render's own multi-photo compositing) -
# a scene planned as one of those two sources without an actual upload
# falls back to the closest Pillow treatment rather than failing (see
# jarvis.reel_generator.scene_render's own fallback logic).
# "typography" is a plain text-focused card - Reel Generator's own
# original, pre-Smart-Visual-Director rendering style, always available.
VISUAL_SOURCE_CHOICES = (
    "ai_generated", "uploaded_photo", "product_photo", "b_roll",
    "video_clip", "animated_background", "typography",
)
DEFAULT_VISUAL_SOURCE = "ai_generated"

# jarvis.story_generator's own original, narrower vocabulary - kept as
# an alias/subset so that package's existing prompts/tests/stored data
# keep working unmodified after promotion (every story_generator value
# is also a valid VISUAL_SOURCE_CHOICES value under a new, more
# Reel-Generator-flavored name - see _VISUAL_TYPE_TO_SOURCE below for
# the mapping jarvis.story_generator's own render call uses).
VISUAL_TYPE_CHOICES = ("photo_style", "product_shot", "lifestyle", "b_roll_style", "illustration")
DEFAULT_VISUAL_TYPE = "photo_style"

# Requirement 8 (AI Reel Generator's own "Visual Style" selector) - a
# whole-REEL style choice (distinct from per-scene visual_type/source
# above), mapped to a jarvis.design_studio.styles.DESIGN_STYLES preset
# by jarvis.reel_generator.scene_render - see that module's own
# _STYLE_BY_VISUAL_STYLE table.
VISUAL_STYLE_CHOICES = (
    "cinematic", "lifestyle", "minimal", "luxury", "soft_feminine",
    "ugc", "emotional", "modern", "bold", "educational",
)
DEFAULT_VISUAL_STYLE = "modern"

# Requirement 4's curated sticker/emoji set - the LLM picks by NAME
# (never an arbitrary emoji string) from this fixed table, each glyph
# hand-verified to actually render (non-blank) with the installed
# Segoe UI Emoji font (C:/Windows/Fonts/seguiemj.ttf) before being
# added here - see jarvis.reel_generator.scene_render's own docstring
# for the rendering side of this contract. "none" means no sticker for
# this scene (requirement 4: "Do not add stickers randomly.").
STICKER_CHOICES: dict[str, str] = {
    "none": "",
    "thinking": "\U0001F914",        # 🤔
    "surprise": "\U0001F633",        # 😳
    "decision": "\u2728",            # ✨
    "money": "\U0001F4B0",           # 💰
    "beauty": "\U0001F484",          # 💄
    "closing_chapter": "\U0001F4E6",  # 📦
    "new_beginning": "\U0001F331",   # 🌱
    "emotional": "\u2764\ufe0f",     # ❤️
    "transformation": "\U0001F4AA",  # 💪
    "goal": "\U0001F3AF",            # 🎯
    "celebration": "\U0001F389",     # 🎉
}
STICKER_NAME_CHOICES = tuple(STICKER_CHOICES.keys())

# Requirement 3/5's text overlay position/animation vocabulary - a fixed
# set for the same "predictable, testable rendering" reason as
# STICKER_CHOICES above, rather than free-form strings
# jarvis.reel_generator.scene_render would have to interpret loosely.
# "word_by_word"/"typewriter" are new for AI Reel Generator's own
# requirement 5 (kinetic typography) - jarvis.story_generator's own
# scenes never request them (its own prompt only offers the original
# fade_in/slide_up/pop/none subset), so this is a purely additive
# vocabulary extension.
TEXT_POSITION_CHOICES = ("top", "center", "bottom")
TEXT_ANIMATION_CHOICES = ("fade_in", "slide_up", "pop", "word_by_word", "typewriter", "none")

# Requirement 5 (AI Reel Generator's own Smart Visual Director brief)
# and jarvis.story_generator's own requirement 5's motion vocabulary -
# matches exactly what jarvis.reel_generator.export's own optional
# motion_by_scene parameter understands (ffmpeg zoompan filter
# directions) - see that module's own docstring for the rendering side.
MOTION_CHOICES = ("zoom_in", "zoom_out", "pan_left", "pan_right", "static")
DEFAULT_MOTION = "static"

# Requirement 13 (AI Reel Generator's own Smart Visual Director brief):
# the transition INTO the next scene - matches exactly what
# jarvis.reel_generator.export's own optional transition_by_scene
# parameter understands (ffmpeg xfade filter types, or "cut" for a
# plain hard concat - see that module's own docstring).
TRANSITION_CHOICES = ("cut", "fade", "zoom", "wipe", "blur")
DEFAULT_TRANSITION = "cut"

# Requirement 6's pacing/lighting vocabulary.
PACING_CHOICES = ("slow", "medium", "fast")
DEFAULT_PACING = "medium"
LIGHTING_CHOICES = ("bright", "warm", "dim", "dramatic", "neutral")
DEFAULT_LIGHTING = "neutral"

# Visual Story Director brief's own camera/shot vocabulary - a fixed
# set for the same "predictable, testable" reason as every other
# *_CHOICES table in this module, rather than free-form camera
# direction jarvis.reel_generator.scene_render would have to interpret
# loosely. Purely descriptive/informational fields shown in the
# storyboard UI (module brief's own "CAMERA:" line) - this codebase has
# no actual camera/cinematography rendering capability (only Pillow
# stills + ffmpeg zoompan motion - see MOTION_CHOICES above, which is
# what ACTUALLY drives the exported video's own camera-like movement);
# camera_shot/camera_movement describe the SHOT the visual (whether
# Pillow-rendered or, when configured, a real generated photo - see
# jarvis.reel_generator.image_generation) is meant to depict.
CAMERA_SHOT_CHOICES = (
    "close_up", "medium_shot", "wide_shot", "extreme_close_up", "over_the_shoulder", "point_of_view",
    # Visual Reel Generator stage's own additional shot types
    # (requirement: "alternate visual types: wide shot / medium shot /
    # close-up / macro / overhead / POV / environment shot / product
    # shot / human action") - added to this SAME vocabulary rather than
    # a separate parallel field, since they describe exactly the same
    # concept (what kind of shot this scene is) as the choices above;
    # "point_of_view" already covers "POV" from that list.
    "macro", "overhead", "environment_shot", "product_shot", "human_action",
)
DEFAULT_CAMERA_SHOT = "medium_shot"
CAMERA_MOVEMENT_CHOICES = ("static", "slow_push_in", "slow_pull_back", "handheld", "pan", "tracking")
DEFAULT_CAMERA_MOVEMENT = "static"

# Visual Story Director brief's own B-roll type vocabulary - describes
# WHAT KIND of supplementary footage/imagery a scene calls for (shown in
# the storyboard UI's own "B-ROLL:" line) - same honesty caveat as
# VISUAL_SOURCE_CHOICES above: no real video-clip library or B-roll
# stock footage exists in this codebase, so this is descriptive
# metadata (and, for a scene whose visual_source ends up as an actual
# generated photo, informs that photo's own prompt), not a real footage
# source. "none" means this scene has no separate B-roll beyond its own
# main visual.
B_ROLL_TYPE_CHOICES = (
    "none", "lifestyle_montage", "product_close_up", "hands_detail", "environment_establishing", "action_sequence",
)
DEFAULT_B_ROLL_TYPE = "none"

# Visual Story Director brief's own music-mood vocabulary - purely
# descriptive metadata (module brief's own requirement 13, "MUSIC MOOD")
# shown in the storyboard UI; no background-music mixing capability
# exists in this codebase, and the exported Reel remains silent in this
# stage (real voice-over/music synchronization was explicitly deferred
# to its own separate later stage, not built as part of the Visual
# Story Director - storing voiceover/music_mood on ScenePlan now means
# the data model doesn't need to change again once that stage exists).
MUSIC_MOOD_CHOICES = ("upbeat", "calm", "emotional", "dramatic", "neutral", "none")
DEFAULT_MUSIC_MOOD = "none"


@dataclass(frozen=True)
class TextCue:
    """One on-screen text overlay within a scene - exact text,
    position, timing window (relative to the scene's OWN start, i.e. 0
    means "right when this scene begins"), and animation style. A scene
    may have zero, one, or several cues -
    jarvis.reel_generator.scene_render renders each cue as its own text
    layer at its own moment, rather than a single static caption for
    the whole scene."""

    text: str
    position: str  # one of TEXT_POSITION_CHOICES
    start_seconds: float  # relative to the scene's own start
    end_seconds: float  # relative to the scene's own start
    animation: str  # one of TEXT_ANIMATION_CHOICES

    @property
    def duration_seconds(self) -> float:
        return round(self.end_seconds - self.start_seconds, 1)


@dataclass(frozen=True)
class ScenePlan:
    """The full per-scene visual plan, one per
    jarvis.reel_generator.storyboard.Scene, matched by `scene_number`.

    `visual_type` (jarvis.story_generator's original, narrower
    VISUAL_TYPE_CHOICES) is the field that package's own prompt/
    construction has always populated; `visual_source` (AI Reel
    Generator's own newer, broader requirement-1 vocabulary,
    VISUAL_SOURCE_CHOICES) defaults to DEFAULT_VISUAL_SOURCE so
    jarvis.story_generator's existing ScenePlan(...) construction (which
    has never passed it) keeps working unmodified - see
    jarvis.reel_generator.storyboard's own scene generation for the
    call site that DOES populate it explicitly. `transition` similarly
    defaults to DEFAULT_TRANSITION ("cut") for the same reason -
    jarvis.story_generator's own per-scene `transition` concept already
    lives on jarvis.reel_generator.storyboard.Scene itself (a DIFFERENT
    field, on a different dataclass - see that dataclass's own
    docstring), so this ScenePlan-level transition is new, AI Reel
    Generator-only vocabulary that Story Generator's own prompt has
    never populated.

    `voiceover`/`camera_shot`/`camera_movement`/`environment`/
    `subject_action`/`b_roll_type`/`text_animation`/`music_mood` are
    the Visual Story Director brief's own additional per-scene fields -
    all default to "" (or the matching *_CHOICES table's own DEFAULT_*
    constant) so existing ScenePlan(...) construction (jarvis
    .story_generator's own, and any already-saved project's stored
    data) keeps working unmodified. `generated_visual_path`/
    `generated_video_path` record where jarvis.reel_generator
    .image_generation's own real, saved output lives for this scene (a
    per-project file path, set by jarvis.reel_generator.scene_render
    once it actually generates/saves an image for this scene - see that
    module's own docstring) - None means no real generated visual exists
    for this scene yet (either generation hasn't run, isn't configured,
    or failed), in which case rendering falls back to this codebase's
    own Pillow treatment."""

    scene_number: int
    visual_type: str  # one of VISUAL_TYPE_CHOICES
    main_visual_prompt: str  # detailed description for the main visual
    supporting_visuals: tuple[str, ...]  # short labels, e.g. "arrow", "before/after split"
    text_cues: tuple[TextCue, ...]
    sticker: str  # one of STICKER_NAME_CHOICES - "none" means no sticker this scene
    sticker_start_seconds: float  # relative to the scene's own start - when the sticker appears
    motion: str  # one of MOTION_CHOICES
    emotion: str  # one or two words, e.g. "hopeful", "anxious"
    pacing: str  # one of PACING_CHOICES
    lighting: str  # one of LIGHTING_CHOICES
    visual_source: str = DEFAULT_VISUAL_SOURCE  # one of VISUAL_SOURCE_CHOICES (AI Reel Generator's requirement 1)
    transition: str = DEFAULT_TRANSITION  # one of TRANSITION_CHOICES - transition INTO the next scene
    is_hook: bool = False  # requirement 6: the first 1-3 seconds get special hook treatment
    voiceover: str = ""  # the spoken narration line for this scene (stored, not yet synthesized - see this dataclass's own docstring)
    camera_shot: str = DEFAULT_CAMERA_SHOT  # one of CAMERA_SHOT_CHOICES - descriptive, shown in the storyboard UI
    camera_movement: str = DEFAULT_CAMERA_MOVEMENT  # one of CAMERA_MOVEMENT_CHOICES - descriptive
    environment: str = ""  # short description of the setting/location, e.g. "cozy bedroom, morning light"
    subject_action: str = ""  # short description of what the subject is doing, e.g. "wrapped in a blanket, sipping tea"
    b_roll_type: str = DEFAULT_B_ROLL_TYPE  # one of B_ROLL_TYPE_CHOICES
    text_animation: str = ""  # free-text animation note for on_screen_text (distinct from a TextCue's own per-cue `animation`)
    music_mood: str = DEFAULT_MUSIC_MOOD  # one of MUSIC_MOOD_CHOICES - descriptive only, no music mixing exists yet
    generated_visual_path: str | None = None  # path to a real jarvis.reel_generator.image_generation-produced image for this scene, if one was generated and saved
    generated_video_path: str | None = None  # reserved for a future real video-clip generation capability - always None today (no such capability exists)
    visual_quality_score: int = 10  # 1-10, see jarvis.reel_generator.visual_quality's own docstring - defaults to 10 (best) so every EXISTING ScenePlan(...) construction (a project saved before this field existed) is treated as already having passed the quality bar, never retroactively flagged

    @property
    def sticker_glyph(self) -> str:
        """The actual emoji character to composite, or "" if this scene
        has no sticker - see STICKER_CHOICES for the name->glyph table."""
        return STICKER_CHOICES.get(self.sticker, "")


@dataclass(frozen=True)
class VisualPlan:
    """A Reel's or Story's complete set of per-scene plans - the
    artifact that gets "passed to the existing scene visual generation
    pipeline so that the actual generated video contains these visual
    elements" (jarvis.reel_generator.scene_render consumes this
    directly, one ScenePlan per Scene). `visual_style`, if set, is the
    whole-Reel style selector (requirement 8, VISUAL_STYLE_CHOICES) -
    empty string for a jarvis.story_generator project, which has no
    equivalent whole-story style selector of its own."""

    scenes: tuple[ScenePlan, ...]
    visual_style: str = ""

    def for_scene(self, scene_number: int) -> ScenePlan | None:
        return next((p for p in self.scenes if p.scene_number == scene_number), None)


def set_scene_generated_video(plan: VisualPlan, scene_number: int, video_path: str | None, *, clear_error: bool = True) -> VisualPlan:
    """NATURAL MOTION / HYBRID mode's own ONE write path for
    `ScenePlan.generated_video_path` (previously always None - see that
    field's own docstring) - called by jarvis.reel_generator.motion_engine
    once it has a real, saved video clip path for this scene (or wants to
    clear a stale one, by passing `video_path=None`). Mutates ONLY the
    one matching scene's own `generated_video_path`, leaving every other
    scene in `plan` - and every other field on the matching scene itself
    - completely untouched, same `dataclasses.replace()`-on-one-scene
    pattern jarvis.reel_generator.storyboard's own regenerate_scene_*()
    helpers already use for single-aspect edits.

    `clear_error` is currently unused by this function itself (there is
    no error field on ScenePlan to clear - a generation failure's error
    message lives on the separate jarvis.reel_generator.scenes
    .SceneMotionClip returned by motion_engine, never mutated into the
    ScenePlan itself) - kept as an explicit, forward-declared parameter
    so a future ScenePlan-level error field (should one ever be added)
    has an obvious, already-documented place to be wired in without
    changing this function's call sites.

    Returns the SAME plan unchanged (a new object, but structurally
    identical) if `scene_number` doesn't match any scene in `plan` -
    never raises for an unknown scene number, matching this codebase's
    general "a caller-supplied scene number that doesn't exist is a
    silent no-op, not an exception" convention for per-scene mutators."""
    updated_scenes = tuple(
        dataclasses.replace(p, generated_video_path=video_path) if p.scene_number == scene_number else p
        for p in plan.scenes
    )
    return dataclasses.replace(plan, scenes=updated_scenes)
