"""Media import/validation for the Professional Video Editor - turns a
file a person picked via an upload dialog (video OR photo, unlike
jarvis.video_studio.storage which is video-only) into a real,
project-local MediaItem with its actual measured properties.

SUPPORTED_VIDEO_EXTENSIONS/SUPPORTED_IMAGE_EXTENSIONS are deliberately
LOCAL, SEPARATE constants - this module never imports, extends, or
monkeypatches jarvis.video_studio.storage.SUPPORTED_EXTENSIONS (see
jarvis.video_editor's own package docstring's isolation rules). The
video extension list happens to share the same literal values as that
sibling module's own set today, which is a coincidence of both modules
targeting the same common container formats, not a dependency between
them - either module's own list can change independently in the future
without touching the other.

Video metadata is probed via jarvis.video_studio.ffmpeg_utils
.probe_video() (pure reuse, read-only call - this module never wraps or
duplicates ffprobe-invoking logic). Photo metadata is read via Pillow
(already a project dependency everywhere else real image work happens -
jarvis.design_studio.render, jarvis.reel_generator.scene_render - never
a new dependency for this module to introduce)."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from jarvis.video_editor.storage import VideoEditorProject, copy_media_into_project
from jarvis.video_studio.ffmpeg_utils import FFmpegError, probe_video

SUPPORTED_VIDEO_EXTENSIONS = frozenset({".mp4", ".mov", ".m4v", ".webm"})
SUPPORTED_IMAGE_EXTENSIONS = frozenset({".jpg", ".jpeg", ".png"})

MediaKind = Literal["video", "photo"]


class MediaImportError(Exception):
    """Raised for an import-layer failure (unsupported extension, a
    video file ffprobe can't read, a photo file Pillow can't open) -
    always with a human-readable message. A LOCAL exception, never
    subclassing jarvis.video_studio.ffmpeg_utils.FFmpegError or
    jarvis.video_editor.storage.VideoEditorStorageError - see this
    module's own isolation rules in the package docstring."""


@dataclass(frozen=True)
class MediaItem:
    """One imported, project-local piece of media - a video clip or a
    photo. `duration_seconds`/`fps` are None for a photo (a still has
    neither); `width`/`height` are always real, measured pixel
    dimensions for both kinds (never guessed/defaulted)."""

    media_item_id: str
    original_filename: str
    stored_path: Path
    kind: MediaKind
    duration_seconds: float | None
    width: int | None
    height: int | None
    fps: float | None


def _media_kind_for_extension(extension: str) -> MediaKind | None:
    extension = extension.lower()
    if extension in SUPPORTED_VIDEO_EXTENSIONS:
        return "video"
    if extension in SUPPORTED_IMAGE_EXTENSIONS:
        return "photo"
    return None


def import_media(path: Path, project: VideoEditorProject, *, media_item_id: str) -> MediaItem:
    """Copies `path` into `project`'s own media directory (via
    jarvis.video_editor.storage.copy_media_into_project() - this
    function never duplicates that copy logic) and probes its real
    properties. Raises MediaImportError for an unsupported extension or
    a file that genuinely can't be read as the kind its extension
    claims - never silently imports a corrupt/unreadable file as if it
    were usable.

    `media_item_id` is generated by the CALLER (jarvis.video_editor's
    own orchestration layer, e.g. a GUI panel or test) rather than by
    this function internally, so the id is known BEFORE the (possibly
    slow) copy+probe work runs - useful for a caller that wants to show
    a placeholder row in a media list immediately and fill it in once
    this function returns, matching this codebase's established
    "caller controls id generation" convention wherever one shows up
    (e.g. jarvis.reel_generator.storage.create_project()'s own
    project_id is generated by jarvis.reel_generator itself, not deep
    inside a shared helper)."""
    from jarvis.video_editor.storage import VideoEditorStorageError

    if not path.is_file():
        raise MediaImportError(f"File not found: {path}")

    kind = _media_kind_for_extension(path.suffix)
    if kind is None:
        supported = ", ".join(
            sorted(e.lstrip(".").upper() for e in SUPPORTED_VIDEO_EXTENSIONS | SUPPORTED_IMAGE_EXTENSIONS)
        )
        raise MediaImportError(f"Unsupported file type '{path.suffix}'. Supported formats: {supported}.")

    try:
        stored_path = copy_media_into_project(project, path)
    except VideoEditorStorageError as e:
        raise MediaImportError(str(e)) from e

    if kind == "video":
        try:
            probe = probe_video(stored_path)
        except FFmpegError as e:
            raise MediaImportError(f"Couldn't read '{path.name}' as a video: {e}") from e
        return MediaItem(
            media_item_id=media_item_id, original_filename=path.name, stored_path=stored_path,
            kind="video", duration_seconds=probe.duration_seconds, width=probe.width,
            height=probe.height, fps=probe.fps,
        )

    # kind == "photo"
    try:
        from PIL import Image, UnidentifiedImageError

        with Image.open(stored_path) as image:
            width, height = image.size
    except (UnidentifiedImageError, OSError) as e:
        raise MediaImportError(f"Couldn't read '{path.name}' as an image: {e}") from e
    return MediaItem(
        media_item_id=media_item_id, original_filename=path.name, stored_path=stored_path,
        kind="photo", duration_seconds=None, width=width, height=height, fps=None,
    )
